< ../config.mk

all:V:
	set -x
	bin/targets | xargs mk

results/sample_indexes.txt:
##	set -x
	mkdir -p `dirname $target`
	wget -q -O - $BASE_URL/ \
	|  grep -v "^<" \
	| grep "/phs" \
	| cut -d'"' -f2 > $target.build \
	&& mv $target.build $target
