< ../config.mk

all:V:
	set -x
	bin/targets | xargs mk

results/%/metadata.xml:
	set -x
	echo "[DEBUGGING] downloading $target"
	mkdir -p `dirname $target`
	wget -q -O - $BASE_URL/$stem/ \
	| grep '\.xml' \
	| grep 'GapExchange' \
	| cut -d'"' -f2 \
	| xargs wget -q -O - > $target.build \
	&& mv $target.build $target || echo "[WARNING] No GapExchange .xml file found for $stem" && rm $target.build
